version: "3.8"
services:
  travellermap:
    image: ghcr.io/erroneousbosch/symfony-base:latest
    container_name: travellermap
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: travellermap.localhost
      XDEBUG_CONFIG: client_host=host.docker.internal
    networks:
      - docker_default
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  docker_default:
    external: true
